name: Fetch releases from S3

on:
  push:
    branches: main
  schedule:
    - cron: "0 1 * * *"

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install boto3

    - name: Get all history from checkfront
      run: cd utils && python3 fetch-releases-from-s3.py

    - name: copy_output_to_build
      run: mkdir publish && cp utils/releases.json publish/

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: publish
